name: OVPSim Integration Tests

on:
  schedule:
    # 6am UTC is 7am Central European Time (CET) or 8am Central European Summer Time (CEST).
    - cron: '0 8 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:
  
  
jobs:
  
  OVPSim_Integration_Tests:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install TFLM dependencies
      run: |
        sudo apt-get install python3-setuptools
        pip3 install wheel
        pip3 install Pillow
        pip3 install Wave
    
    - name: Download TFLM
      working-directory: ./Integration/TFLM
      run: git clone https://github.com/tensorflow/tflite-micro.git
      
    - name: Patch TFLM
      working-directory: ./Integration/TFLM/tflite-micro
      run: git apply ../muriscv_nn.patch
      
    - name: Build Scalar muRISCV-NN with gcc
      working-directory: ./Scripts
      run: ./build_one.sh GCC rv32gc
      
    - name: TFLM Integration Test for Scalar muRISCV-NN with gcc
      working-directory: ./Integration/TFLM/tflite-micro
      run: ../tflm_integration_tests.sh OFF OFF RELEASE gcc rv32gc 1024 OVPSim
      
    - name: Build Scalar muRISCV-NN with llvm
      working-directory: ./Scripts
      run: ./build_one.sh LLVM rv32gc
      
    - name: TFLM Integration Test for Scalar muRISCV-NN with llvm
      working-directory: ./Integration/TFLM/tflite-micro
      run: ../tflm_integration_tests.sh OFF OFF RELEASE llvm rv32gc 1024 OVPSim

