name: Unit Tests

on:
  schedule:
    # 6am UTC is 7am Central European Time (CET) or 8am Central European Summer Time (CEST).
    - cron: '0 8 * * *'
    
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Test_Scalar:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2  
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Download Spike Cache
      id: cache-Spike
      uses: actions/cache@v3
      env:
          cache-name: cache-spike-binaries
      with:
          path: ./Sim/Spike/bin
          key: spike-binaries-${{ steps.date.outputs.date }}
          restore-keys: |
            spike-binaries-
          
    - name: Download GCC Cache
      id: cache-GCC
      uses: actions/cache@v3
      env:
          cache-name: cache-gcc-binaries
      with:
          path: ./Toolchain
          key: gcc-binaries-${{ steps.date.outputs.date }}
          restore-keys: |
            gcc-binaries-
          
    - name: Install Spike Dependencies
      run: |
        sudo apt-get install libboost-all-dev
        sudo apt-get install device-tree-compiler
        
    - name: Run Scalar tests
      working-directory: ./Scripts
      run: |
        ./test_scalar.sh
        
  Test_Packed:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2  
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Download Spike Cache
      id: cache-Spike
      uses: actions/cache@v3
      env:
          cache-name: cache-spike-binaries
      with:
          path: ./Sim/Spike/bin
          key: spike-binaries-${{ steps.date.outputs.date }}
          restore-keys: |
            spike-binaries-
          
    - name: Download GCC Cache
      id: cache-GCC
      uses: actions/cache@v3
      env:
          cache-name: cache-gcc-binaries
      with:
          path: ./Toolchain
          key: gcc-binaries-${{ steps.date.outputs.date }}
          restore-keys: |
            gcc-binaries-
          
    - name: Install Spike Dependencies
      run: |
        sudo apt-get install libboost-all-dev
        sudo apt-get install device-tree-compiler
    
    - name: Run Packed Tests
      working-directory: ./Scripts
      run: |
        ./test_packed.sh
        
  Test_Vector:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2  
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Download Spike Cache
      id: cache-Spike
      uses: actions/cache@v3
      env:
          cache-name: cache-spike-binaries
      with:
          path: ./Sim/Spike/bin
          key: spike-binaries-${{ steps.date.outputs.date }}
          restore-keys: |
            spike-binaries-
          
    - name: Download GCC Cache
      id: cache-GCC
      uses: actions/cache@v3
      env:
          cache-name: cache-gcc-binaries
      with:
          path: ./Toolchain
          key: gcc-binaries-${{ steps.date.outputs.date }}
          restore-keys: |
            gcc-binaries-
          
    - name: Install Spike Dependencies
      run: |
        sudo apt-get install libboost-all-dev
        sudo apt-get install device-tree-compiler
    
    - name: Run Vector Tests
      working-directory: ./Scripts
      run: |
        ./test_vector.sh
    

